version: '3.9'

services:
  go-boilerplate:
    build: .
    container_name: go-boilerplate-staging
    restart: unless-stopped
    ports:
      - '${APP_PORT}:${APP_PORT}'
    env_file:
      - .env
    environment:
      # Production environment variables
      - APP_ENV=production
      - APP_PORT=${APP_PORT}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}

      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TLS=${REDIS_TLS}

      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
      - STORAGE_SECRET_KEY=${STORAGE_SECRET_KEY}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
      - STORAGE_USE_SSL=${STORAGE_USE_SSL}
      - STORAGE_PUBLIC_URL=${STORAGE_PUBLIC_URL}

      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_EMAIL=${MAIL_FROM_EMAIL}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_RESET_PASSWORD_URL=${MAIL_RESET_PASSWORD_URL}

    extra_hosts:
      - 'host.docker.internal:host-gateway'

    networks:
      - traefik

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api-boilerplate.rule=Host(`api-boilerplate.yourwebsite.com`)'
      - 'traefik.http.routers.api-boilerplate.entrypoints=websecure'
      - 'traefik.http.services.api-boilerplate.loadbalancer.server.port=3098'
      - 'traefik.http.routers.api-boilerplate.tls.certresolver=letsencryptresolver'

networks:
  traefik:
    external: true
