// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-boilerplate/ent/predicate"
	"go-boilerplate/ent/profiles"
	"go-boilerplate/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProfilesUpdate is the builder for updating Profiles entities.
type ProfilesUpdate struct {
	config
	hooks    []Hook
	mutation *ProfilesMutation
}

// Where appends a list predicates to the ProfilesUpdate builder.
func (_u *ProfilesUpdate) Where(ps ...predicate.Profiles) *ProfilesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ProfilesUpdate) SetName(v string) *ProfilesUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProfilesUpdate) SetNillableName(v *string) *ProfilesUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetImageUrl sets the "imageUrl" field.
func (_u *ProfilesUpdate) SetImageUrl(v string) *ProfilesUpdate {
	_u.mutation.SetImageUrl(v)
	return _u
}

// SetNillableImageUrl sets the "imageUrl" field if the given value is not nil.
func (_u *ProfilesUpdate) SetNillableImageUrl(v *string) *ProfilesUpdate {
	if v != nil {
		_u.SetImageUrl(*v)
	}
	return _u
}

// ClearImageUrl clears the value of the "imageUrl" field.
func (_u *ProfilesUpdate) ClearImageUrl() *ProfilesUpdate {
	_u.mutation.ClearImageUrl()
	return _u
}

// SetBirthDate sets the "birthDate" field.
func (_u *ProfilesUpdate) SetBirthDate(v string) *ProfilesUpdate {
	_u.mutation.SetBirthDate(v)
	return _u
}

// SetNillableBirthDate sets the "birthDate" field if the given value is not nil.
func (_u *ProfilesUpdate) SetNillableBirthDate(v *string) *ProfilesUpdate {
	if v != nil {
		_u.SetBirthDate(*v)
	}
	return _u
}

// ClearBirthDate clears the value of the "birthDate" field.
func (_u *ProfilesUpdate) ClearBirthDate() *ProfilesUpdate {
	_u.mutation.ClearBirthDate()
	return _u
}

// SetAddress sets the "address" field.
func (_u *ProfilesUpdate) SetAddress(v string) *ProfilesUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *ProfilesUpdate) SetNillableAddress(v *string) *ProfilesUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *ProfilesUpdate) ClearAddress() *ProfilesUpdate {
	_u.mutation.ClearAddress()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ProfilesUpdate) SetCreatedAt(v time.Time) *ProfilesUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ProfilesUpdate) SetNillableCreatedAt(v *time.Time) *ProfilesUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProfilesUpdate) SetUpdatedAt(v time.Time) *ProfilesUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ProfilesUpdate) SetNillableUpdatedAt(v *time.Time) *ProfilesUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ProfilesUpdate) SetUserID(id uuid.UUID) *ProfilesUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProfilesUpdate) SetUser(v *User) *ProfilesUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ProfilesMutation object of the builder.
func (_u *ProfilesUpdate) Mutation() *ProfilesMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProfilesUpdate) ClearUser() *ProfilesUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProfilesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProfilesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProfilesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProfilesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProfilesUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Profiles.user"`)
	}
	return nil
}

func (_u *ProfilesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(profiles.Table, profiles.Columns, sqlgraph.NewFieldSpec(profiles.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(profiles.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageUrl(); ok {
		_spec.SetField(profiles.FieldImageUrl, field.TypeString, value)
	}
	if _u.mutation.ImageUrlCleared() {
		_spec.ClearField(profiles.FieldImageUrl, field.TypeString)
	}
	if value, ok := _u.mutation.BirthDate(); ok {
		_spec.SetField(profiles.FieldBirthDate, field.TypeString, value)
	}
	if _u.mutation.BirthDateCleared() {
		_spec.ClearField(profiles.FieldBirthDate, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(profiles.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(profiles.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(profiles.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(profiles.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profiles.UserTable,
			Columns: []string{profiles.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profiles.UserTable,
			Columns: []string{profiles.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profiles.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProfilesUpdateOne is the builder for updating a single Profiles entity.
type ProfilesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfilesMutation
}

// SetName sets the "name" field.
func (_u *ProfilesUpdateOne) SetName(v string) *ProfilesUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProfilesUpdateOne) SetNillableName(v *string) *ProfilesUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetImageUrl sets the "imageUrl" field.
func (_u *ProfilesUpdateOne) SetImageUrl(v string) *ProfilesUpdateOne {
	_u.mutation.SetImageUrl(v)
	return _u
}

// SetNillableImageUrl sets the "imageUrl" field if the given value is not nil.
func (_u *ProfilesUpdateOne) SetNillableImageUrl(v *string) *ProfilesUpdateOne {
	if v != nil {
		_u.SetImageUrl(*v)
	}
	return _u
}

// ClearImageUrl clears the value of the "imageUrl" field.
func (_u *ProfilesUpdateOne) ClearImageUrl() *ProfilesUpdateOne {
	_u.mutation.ClearImageUrl()
	return _u
}

// SetBirthDate sets the "birthDate" field.
func (_u *ProfilesUpdateOne) SetBirthDate(v string) *ProfilesUpdateOne {
	_u.mutation.SetBirthDate(v)
	return _u
}

// SetNillableBirthDate sets the "birthDate" field if the given value is not nil.
func (_u *ProfilesUpdateOne) SetNillableBirthDate(v *string) *ProfilesUpdateOne {
	if v != nil {
		_u.SetBirthDate(*v)
	}
	return _u
}

// ClearBirthDate clears the value of the "birthDate" field.
func (_u *ProfilesUpdateOne) ClearBirthDate() *ProfilesUpdateOne {
	_u.mutation.ClearBirthDate()
	return _u
}

// SetAddress sets the "address" field.
func (_u *ProfilesUpdateOne) SetAddress(v string) *ProfilesUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *ProfilesUpdateOne) SetNillableAddress(v *string) *ProfilesUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *ProfilesUpdateOne) ClearAddress() *ProfilesUpdateOne {
	_u.mutation.ClearAddress()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ProfilesUpdateOne) SetCreatedAt(v time.Time) *ProfilesUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ProfilesUpdateOne) SetNillableCreatedAt(v *time.Time) *ProfilesUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProfilesUpdateOne) SetUpdatedAt(v time.Time) *ProfilesUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ProfilesUpdateOne) SetNillableUpdatedAt(v *time.Time) *ProfilesUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ProfilesUpdateOne) SetUserID(id uuid.UUID) *ProfilesUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProfilesUpdateOne) SetUser(v *User) *ProfilesUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ProfilesMutation object of the builder.
func (_u *ProfilesUpdateOne) Mutation() *ProfilesMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProfilesUpdateOne) ClearUser() *ProfilesUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ProfilesUpdate builder.
func (_u *ProfilesUpdateOne) Where(ps ...predicate.Profiles) *ProfilesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProfilesUpdateOne) Select(field string, fields ...string) *ProfilesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Profiles entity.
func (_u *ProfilesUpdateOne) Save(ctx context.Context) (*Profiles, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProfilesUpdateOne) SaveX(ctx context.Context) *Profiles {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProfilesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProfilesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProfilesUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Profiles.user"`)
	}
	return nil
}

func (_u *ProfilesUpdateOne) sqlSave(ctx context.Context) (_node *Profiles, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(profiles.Table, profiles.Columns, sqlgraph.NewFieldSpec(profiles.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Profiles.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profiles.FieldID)
		for _, f := range fields {
			if !profiles.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != profiles.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(profiles.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageUrl(); ok {
		_spec.SetField(profiles.FieldImageUrl, field.TypeString, value)
	}
	if _u.mutation.ImageUrlCleared() {
		_spec.ClearField(profiles.FieldImageUrl, field.TypeString)
	}
	if value, ok := _u.mutation.BirthDate(); ok {
		_spec.SetField(profiles.FieldBirthDate, field.TypeString, value)
	}
	if _u.mutation.BirthDateCleared() {
		_spec.ClearField(profiles.FieldBirthDate, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(profiles.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(profiles.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(profiles.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(profiles.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profiles.UserTable,
			Columns: []string{profiles.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profiles.UserTable,
			Columns: []string{profiles.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Profiles{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profiles.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
