// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-boilerplate/ent/profiles"
	"go-boilerplate/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Profiles is the model entity for the Profiles schema.
type Profiles struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ImageUrl holds the value of the "imageUrl" field.
	ImageUrl string `json:"imageUrl,omitempty"`
	// BirthDate holds the value of the "birthDate" field.
	BirthDate string `json:"birthDate,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProfilesQuery when eager-loading is set.
	Edges         ProfilesEdges `json:"edges"`
	user_profiles *uuid.UUID
	selectValues  sql.SelectValues
}

// ProfilesEdges holds the relations/edges for other nodes in the graph.
type ProfilesEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProfilesEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Profiles) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case profiles.FieldName, profiles.FieldImageUrl, profiles.FieldBirthDate, profiles.FieldAddress:
			values[i] = new(sql.NullString)
		case profiles.FieldCreatedAt, profiles.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case profiles.FieldID:
			values[i] = new(uuid.UUID)
		case profiles.ForeignKeys[0]: // user_profiles
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Profiles fields.
func (_m *Profiles) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case profiles.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case profiles.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case profiles.FieldImageUrl:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field imageUrl", values[i])
			} else if value.Valid {
				_m.ImageUrl = value.String
			}
		case profiles.FieldBirthDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field birthDate", values[i])
			} else if value.Valid {
				_m.BirthDate = value.String
			}
		case profiles.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case profiles.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case profiles.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case profiles.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_profiles", values[i])
			} else if value.Valid {
				_m.user_profiles = new(uuid.UUID)
				*_m.user_profiles = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Profiles.
// This includes values selected through modifiers, order, etc.
func (_m *Profiles) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Profiles entity.
func (_m *Profiles) QueryUser() *UserQuery {
	return NewProfilesClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Profiles.
// Note that you need to call Profiles.Unwrap() before calling this method if this Profiles
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Profiles) Update() *ProfilesUpdateOne {
	return NewProfilesClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Profiles entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Profiles) Unwrap() *Profiles {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Profiles is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Profiles) String() string {
	var builder strings.Builder
	builder.WriteString("Profiles(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("imageUrl=")
	builder.WriteString(_m.ImageUrl)
	builder.WriteString(", ")
	builder.WriteString("birthDate=")
	builder.WriteString(_m.BirthDate)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProfilesSlice is a parsable slice of Profiles.
type ProfilesSlice []*Profiles
