// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-boilerplate/ent/profiles"
	"go-boilerplate/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProfilesCreate is the builder for creating a Profiles entity.
type ProfilesCreate struct {
	config
	mutation *ProfilesMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ProfilesCreate) SetName(v string) *ProfilesCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetImageUrl sets the "imageUrl" field.
func (_c *ProfilesCreate) SetImageUrl(v string) *ProfilesCreate {
	_c.mutation.SetImageUrl(v)
	return _c
}

// SetNillableImageUrl sets the "imageUrl" field if the given value is not nil.
func (_c *ProfilesCreate) SetNillableImageUrl(v *string) *ProfilesCreate {
	if v != nil {
		_c.SetImageUrl(*v)
	}
	return _c
}

// SetBirthDate sets the "birthDate" field.
func (_c *ProfilesCreate) SetBirthDate(v string) *ProfilesCreate {
	_c.mutation.SetBirthDate(v)
	return _c
}

// SetNillableBirthDate sets the "birthDate" field if the given value is not nil.
func (_c *ProfilesCreate) SetNillableBirthDate(v *string) *ProfilesCreate {
	if v != nil {
		_c.SetBirthDate(*v)
	}
	return _c
}

// SetAddress sets the "address" field.
func (_c *ProfilesCreate) SetAddress(v string) *ProfilesCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_c *ProfilesCreate) SetNillableAddress(v *string) *ProfilesCreate {
	if v != nil {
		_c.SetAddress(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProfilesCreate) SetCreatedAt(v time.Time) *ProfilesCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProfilesCreate) SetNillableCreatedAt(v *time.Time) *ProfilesCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProfilesCreate) SetUpdatedAt(v time.Time) *ProfilesCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProfilesCreate) SetNillableUpdatedAt(v *time.Time) *ProfilesCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProfilesCreate) SetID(v uuid.UUID) *ProfilesCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProfilesCreate) SetNillableID(v *uuid.UUID) *ProfilesCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ProfilesCreate) SetUserID(id uuid.UUID) *ProfilesCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ProfilesCreate) SetUser(v *User) *ProfilesCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ProfilesMutation object of the builder.
func (_c *ProfilesCreate) Mutation() *ProfilesMutation {
	return _c.mutation
}

// Save creates the Profiles in the database.
func (_c *ProfilesCreate) Save(ctx context.Context) (*Profiles, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProfilesCreate) SaveX(ctx context.Context) *Profiles {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProfilesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProfilesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProfilesCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := profiles.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := profiles.DefaultUpdatedAt
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := profiles.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProfilesCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Profiles.name"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Profiles.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Profiles.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Profiles.user"`)}
	}
	return nil
}

func (_c *ProfilesCreate) sqlSave(ctx context.Context) (*Profiles, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProfilesCreate) createSpec() (*Profiles, *sqlgraph.CreateSpec) {
	var (
		_node = &Profiles{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(profiles.Table, sqlgraph.NewFieldSpec(profiles.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(profiles.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ImageUrl(); ok {
		_spec.SetField(profiles.FieldImageUrl, field.TypeString, value)
		_node.ImageUrl = value
	}
	if value, ok := _c.mutation.BirthDate(); ok {
		_spec.SetField(profiles.FieldBirthDate, field.TypeString, value)
		_node.BirthDate = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(profiles.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(profiles.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(profiles.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profiles.UserTable,
			Columns: []string{profiles.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_profiles = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProfilesCreateBulk is the builder for creating many Profiles entities in bulk.
type ProfilesCreateBulk struct {
	config
	err      error
	builders []*ProfilesCreate
}

// Save creates the Profiles entities in the database.
func (_c *ProfilesCreateBulk) Save(ctx context.Context) ([]*Profiles, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Profiles, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProfilesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProfilesCreateBulk) SaveX(ctx context.Context) []*Profiles {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProfilesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProfilesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
