// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-boilerplate/ent/profiles"
	"go-boilerplate/ent/schema"
	"go-boilerplate/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	profilesFields := schema.Profiles{}.Fields()
	_ = profilesFields
	// profilesDescCreatedAt is the schema descriptor for created_at field.
	profilesDescCreatedAt := profilesFields[5].Descriptor()
	// profiles.DefaultCreatedAt holds the default value on creation for the created_at field.
	profiles.DefaultCreatedAt = profilesDescCreatedAt.Default.(time.Time)
	// profilesDescUpdatedAt is the schema descriptor for updated_at field.
	profilesDescUpdatedAt := profilesFields[6].Descriptor()
	// profiles.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	profiles.DefaultUpdatedAt = profilesDescUpdatedAt.Default.(time.Time)
	// profilesDescID is the schema descriptor for id field.
	profilesDescID := profilesFields[0].Descriptor()
	// profiles.DefaultID holds the default value on creation for the id field.
	profiles.DefaultID = profilesDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
