// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-boilerplate/ent/comments"
	"go-boilerplate/ent/schema"
	"go-boilerplate/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentsFields := schema.Comments{}.Fields()
	_ = commentsFields
	// commentsDescCreatedAt is the schema descriptor for created_at field.
	commentsDescCreatedAt := commentsFields[2].Descriptor()
	// comments.DefaultCreatedAt holds the default value on creation for the created_at field.
	comments.DefaultCreatedAt = commentsDescCreatedAt.Default.(time.Time)
	// commentsDescUpdatedAt is the schema descriptor for updated_at field.
	commentsDescUpdatedAt := commentsFields[3].Descriptor()
	// comments.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comments.DefaultUpdatedAt = commentsDescUpdatedAt.Default.(time.Time)
	// commentsDescID is the schema descriptor for id field.
	commentsDescID := commentsFields[0].Descriptor()
	// comments.DefaultID holds the default value on creation for the id field.
	comments.DefaultID = commentsDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
